name: Boom SLA check (manual)

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      LOGIN_URL:       ${{ vars.LOGIN_URL }}
      LOGIN_METHOD:    ${{ vars.LOGIN_METHOD }}
      MESSAGES_URL:    ${{ vars.MESSAGES_URL }}
      MESSAGES_METHOD: ${{ vars.MESSAGES_METHOD }}
      SLA_MINUTES:     ${{ vars.SLA_MINUTES }}
      DEBUG:           ${{ vars.DEBUG }}
      DEBUG_MESSAGES:  ${{ vars.DEBUG_MESSAGES }}
      APP_URL: https://app.boomnow.com
      SMTP_HOST:       ${{ secrets.SMTP_HOST }}
      SMTP_PORT:       ${{ secrets.SMTP_PORT }}
      SMTP_USER:       ${{ secrets.SMTP_USER }}
      SMTP_PASS:       ${{ secrets.SMTP_PASS }}
      ALERT_TO:        ${{ secrets.ALERT_TO }}
      ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}
      LINK_SECRET:     ${{ secrets.LINK_SECRET }}
      BOOM_USER:       ${{ secrets.BOOM_USER }}
      BOOM_PASS:       ${{ secrets.BOOM_PASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: .
        run: |
          ls -la
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi
      - name: Debug conversations endpoint (with auth)
        shell: bash
        env:
          CONVERSATIONS_URL: ${{ vars.CONVERSATIONS_URL }}
          MESSAGES_URL: ${{ vars.MESSAGES_URL }}
          BOOM_BEARER: ${{ secrets.BOOM_BEARER }}
          BOOM_COOKIE: ${{ secrets.BOOM_COOKIE }}
        run: |
          set -euo pipefail
          echo "CONVERSATIONS_URL=${CONVERSATIONS_URL}"
          echo "MESSAGES_URL=${MESSAGES_URL}"
          echo "--- RESPONSE STATUS + HEADERS ---"

          # Build a single header string safely (no embedded quotes),
          # and disable curl's URL globbing to avoid {} / [] issues.
          HEADER=""
          if [[ -n "${BOOM_BEARER:-}" ]]; then
            HEADER="Authorization: Bearer ${BOOM_BEARER}"
          elif [[ -n "${BOOM_COOKIE:-}" ]]; then
            HEADER="Cookie: ${BOOM_COOKIE}"
          fi

          if [[ -n "$HEADER" ]]; then
            curl --globoff -sS -D - -o /dev/null -H "$HEADER" "$CONVERSATIONS_URL"
          else
            curl --globoff -sS -D - -o /dev/null "$CONVERSATIONS_URL"
          fi

          # Optional: also sanity-check the messages endpoint
          if [[ -n "${MESSAGES_URL:-}" ]]; then
            echo
            if [[ -n "$HEADER" ]]; then
              curl --globoff -sS -D - -o /dev/null -H "$HEADER" "$MESSAGES_URL"
            else
              curl --globoff -sS -D - -o /dev/null "$MESSAGES_URL"
            fi
          fi

      - name: Run SLA checker
        working-directory: .
        run: node ./check.mjs
