name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation:
        description: 'Conversation URL (Boom "Open in Boom" link or direct /guest-experience/sales/..)'
        required: true
  schedule:
    - cron: '*/10 * * * *' # example: every 10 minutes

jobs:
  run-check:
    runs-on: ubuntu-latest
    env:
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      FROM_NAME: ${{ secrets.FROM_NAME }}
      ROHIT_EMAIL: ${{ secrets.ROHIT_EMAIL }}
      BREACH_MINUTES: 5
      CONVERSATION_URL: ${{ github.event.inputs.conversation || secrets.DEFAULT_CONVERSATION_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (cached)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (ci if lockfile exists)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        run: node check.js

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: |
            /tmp/shot_before.png
            /tmp/shot_after.png
            /tmp/page_dump.html
          if-no-files-found: ignore
