name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation_url:
        description: "Boom conversation URL"
        required: true
        type: string

jobs:
  run-check:
    runs-on: ubuntu-latest

    env:
      # Secrets
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}
      ALERT_TO: ${{ secrets.ALERT_TO }}
      AGENT_SIDE: ${{ secrets.AGENT_SIDE }}
      # Input (also read by the script)
      CONVERSATION_URL: ${{ inputs.conversation_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        run: node check.js --conversation "${{ inputs.conversation_url }}"

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: |
            /tmp/shot_*.png
            /tmp/page_*.html
          if-no-files-found: ignore
