name: Boom SLA check

on:
  repository_dispatch:
    types: [boom_check]
  workflow_dispatch:
    inputs:
      conversationUrl:
        description: "Boom conversation URL"
        required: true
        type: string

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install deps (works whether or not you have a lockfile)
      - name: Install dependencies
        run: npm ci || npm install --no-audit --no-fund

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        env:
          CONVERSATION_URL: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.conversationUrl || inputs.conversationUrl }}
          BOOM_USER: ${{ secrets.BOOM_USER }}
          BOOM_PASS: ${{ secrets.BOOM_PASS }}
          ROHIT_EMAIL: ${{ secrets.ROHIT_EMAIL }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          FROM_NAME: ${{ secrets.FROM_NAME }}
          REPLY_TO: ${{ secrets.REPLY_TO }}
          # optional manual override if detection struggles: "left" or "right"
          AGENT_SIDE: ${{ vars.AGENT_SIDE || secrets.AGENT_SIDE }}
        run: node check.js

      - name: Upload debug artifacts (screenshots & HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: boom-debug-${{ github.run_id }}
          path: |
            /tmp/nomsg_*.png
            /tmp/nomsg_*.html
            /tmp/before_login*.png
            /tmp/after_login*.png
            /tmp/after_regoto*.png
          if-no-files-found: warn
          retention-days: 3
