name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation:
        description: "Full Boom conversation URL"
        required: true
        type: string
      sla_minutes:
        description: "SLA minutes (override)"
        required: false
        type: string

jobs:
  run-check:
    runs-on: ubuntu-latest
    env:
      CONVERSATION_URL: ${{ inputs.conversation }}
      SLA_MINUTES: ${{ inputs.sla_minutes }}
      # Secrets you already have:
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      ALERT_TO:   ${{ secrets.ALERT_TO }}
      ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}
      AGENT_SIDE: ${{ secrets.AGENT_SIDE }}
      TZ: Asia/Riyadh

    steps:
      - name: Set up job
        run: echo "Starting Boom SLA check"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playw*** checker
        run: |
          if [ -n "${CONVERSATION_URL:-}" ]; then
            node check.mjs
          else
            echo "No CONVERSATION_URL provided. Skipping."
          fi

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: boom-sla-artifacts
          path: |
            /tmp/boom-*.png
            /tmp/boom-*.html
            /tmp/boom-*.json
          if-no-files-found: warn
