name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation:
        description: "Boom conversation URL (or tracking URL)"
        required: true
        type: string
  repository_dispatch:
    types: [boom_check]

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      CONVERSATION_URL: ${{ github.event.inputs.conversation || github.event.client_payload.conversation || '' }}
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      FROM_NAME: ${{ secrets.FROM_NAME }}
      ROHIT_EMAIL: ${{ secrets.ROHIT_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (ci if lockfile exists)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        run: node check.js

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: |
            /tmp/shot_t1.png
            /tmp/shot_t2.png
            /tmp/page_t1.html
            /tmp/page_t2.html
          if-no-files-found: warn
