name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation_url:
        description: "Boom conversation URL or tracked link"
        required: false
        type: string

permissions:
  contents: read

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # Boom login
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}

      # Email / SMTP
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      FROM_NAME:  ${{ secrets.FROM_NAME }}
      ROHIT_EMAIL: ${{ secrets.ROHIT_EMAIL }}

      # Conversation URL (input wins; secret as fallback)
      CONVERSATION_URL: ${{ inputs.conversation_url || secrets.CONVERSATION_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use cached setup ONLY if a lockfile exists.
      - name: Setup Node.js (cached)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json
            **/yarn.lock

      - name: Setup Node.js (no cache)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install deps; prefer npm ci when a lockfile exists.
      - name: Install dependencies (ci)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != '' }}
        run: npm ci --no-fund --no-audit

      - name: Install dependencies (install)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') == '' }}
        run: npm i --no-fund --no-audit

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        run: node check.js

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pages
          path: |
            /tmp/shot_*.png
            /tmp/page_*.html
          if-no-files-found: ignore
