name: Boom SLA (API, REST)

on:
  workflow_dispatch:
    inputs:
      conversation_urls:
        description: "One or more Boom conversation API URLs (GET). You can paste multiple separated by newline/space/comma."
        required: true
      sla_minutes:
        description: "SLA minutes threshold"
        required: false
        default: "5"
      alert_to:
        description: "Optional email to override ALERT_TO secret for this run"
        required: false
        default: ""

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Run SLA checker
        env:
          # --- Required secrets you already have configured ---
          BOOM_EMAIL: ${{ secrets.BOOM_USER }}
          BOOM_PASSWORD: ${{ secrets.BOOM_PASS }}

          # Optional: if Boom uses a CSRF cookie endpoint (Laravel style).
          # If you don't have it, the script will still try login directly.
          BOOM_CSRF_URL: https://app.boomnow.com/sanctum/csrf-cookie

          # Login endpoint (POST)
          BOOM_LOGIN_URL: https://app.boomnow.com/api/login

          # SMTP (you already have these)
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ALERT_TO_DEFAULT: ${{ secrets.ALERT_TO }}
          ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}

          # Inputs
          DISPATCH_CONVERSATION_URLS: ${{ github.event.inputs.conversation_urls }}
          DISPATCH_SLA_MINUTES: ${{ github.event.inputs.sla_minutes }}
          DISPATCH_ALERT_TO: ${{ github.event.inputs.alert_to }}
        run: |
          node check.mjs
