name: Boom SLA (API, REST)

on:
  workflow_dispatch:
    inputs:
      conversation_urls:
        description: "One or more conversation URLs/UUIDs (comma/space separated)"
        required: false
      sla_minutes:
        description: "SLA minutes"
        required: false
        default: "5"
  schedule:
    - cron: "*/5 * * * *" # optional: run every 5 minutes

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      # 🔽 The script reads these envs
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}

      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}

      ALERT_TO: ${{ secrets.ALERT_TO }}
      ALERT_CC: ${{ secrets.ALERT_CC }}
      ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}

      # 🔽 Provide conversation URLs from (in order): manual input, repo Variables, repo Secrets
      CONVERSATION_URLS: ${{ inputs.conversation_urls || vars.CONVERSATION_URLS || secrets.CONVERSATION_URLS }}
      SLA_MINUTES: ${{ inputs.sla_minutes || vars.SLA_MINUTES || '5' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install deps
        run: npm install nodemailer

      - name: Run SLA checker
        run: node check.mjs
