name: Boom check (cron → Azure Function)

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      FUNC_BASE: ${{ secrets.AZURE_FUNCTION_HOST }}
      FUNC_NAME: boom-notify
      FUNC_CODE: ${{ secrets.AZURE_FUNCTION_CODE }}
      SHARED_SECRET: ${{ secrets.BOOM_SHARED_SECRET }}
    steps:
      - name: Call check
        run: |
          set -euo pipefail
          URL="https://${FUNC_BASE}/api/${FUNC_NAME}?code=${FUNC_CODE}"
          BODY='{"event":"scheduled_check"}'
          curl -sS -X POST "$URL" \
            -H "Content-Type: application/json" \
            -H "X-Shared-Secret: ${SHARED_SECRET}" \
            -d "$BODY"

