name: Boom SLA Check

on:
  # Triggered by Power Automate via Repository Dispatch
  repository_dispatch:
    types: [boom-sla-check]
  # Optional manual run for testing
  workflow_dispatch: {}

permissions:
  contents: read

env:
  # === Tuning switches ===
  # Count AI suggestions as agent replies? "false" | "approved" | "true"
  COUNT_AI_SUGGESTION_AS_AGENT: "approved"  # <-- FIX: count only agent-approved AI
  # SLA window in minutes
  SLA_MINUTES: "${{ vars.SLA_MINUTES || 5 }}"
  # Set DEBUG=1 in repository Variables to get console tables
  DEBUG: "${{ vars.DEBUG }}"

  # === Email ===
  ALERT_TO: "${{ vars.ALERT_TO }}"
  ALERT_FROM: "${{ vars.ALERT_FROM }}"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run SLA checker
        id: check
        run: node check.mjs
        env:
          # Pass the event payload path automatically provided by Actions
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          # Optional: allow fallback URL if you want to test without repository_dispatch
          CONVERSATION_URL: "${{ vars.CONVERSATION_URL }}"
          # SMTP from repo/org secrets
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      - name: Send alert email (only on breach)
        if: steps.check.outputs.breach == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          subject: ${{ steps.check.outputs.email_subject }}
          to: ${{ env.ALERT_TO }}
          from: ${{ env.ALERT_FROM }}
          content_type: text/plain; charset=utf-8
          body: ${{ steps.check.outputs.email_body }}
