name: Boom SLA check

on:
  workflow_dispatch:
    inputs:
      conversation_url:
        description: "Boom conversation URL or tracked link"
        required: false
        type: string

permissions:
  contents: read

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # App creds
      BOOM_USER: ${{ secrets.BOOM_USER }}
      BOOM_PASS: ${{ secrets.BOOM_PASS }}

      # Email / SMTP
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      FROM_NAME:  ${{ secrets.FROM_NAME }}
      ROHIT_EMAIL: ${{ secrets.ROHIT_EMAIL }}

      # Conversation URL: workflow input wins; falls back to secret if present
      CONVERSATION_URL: ${{ inputs.conversation_url || secrets.CONVERSATION_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm i --no-fund --no-audit

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright checker
        run: node check.js

      - name: Upload page artifacts (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pages
          path: |
            /tmp/shot_*.png
            /tmp/page_*.html
          if-no-files-found: ignore
