name: Boom SLA (API, REST)
on:
# Keep the existing 5-minute schedule so the checker still runs regularly
schedule:
- cron: "*/5 * * * *" # every 5 minutes
# Allow manual runs from the Actions UI with an optional conversation input
workflow
_dispatch:
inputs:
conversation:
DEFAULT
description: "Conversation (UI URL / API URL / UUID). Optional if
CONVERSATION
_ID repo variable is set."
_
required: false
# Accept repository_dispatch events from Power Automate. Any event_type will be honoured.
repository_dispatch:
jobs:
check:
runs-on: ubuntu-latest
timeout-minutes: 6
env:
BOOM
_
USER: ${{ secrets.BOOM_USER }}
BOOM
_
PASS: ${{ secrets.BOOM_PASS }}
SMTP
_
HOST: ${{ secrets.SMTP_HOST }}
SMTP
_
PORT: ${{ secrets.SMTP_PORT }}
SMTP
_
USER: ${{ secrets.SMTP_USER }}
SMTP
_
PASS: ${{ secrets.SMTP_PASS }}
ALERT
_
TO: ${{ secrets.ALERT_TO }}
ALERT
FROM
_
_
NAME: ${{ secrets.ALERT_
FROM
_NAME }}
LOGIN
_
URL: "https://app.boomnow.com/api/login"
LOGIN
METHOD: "POST"
_
LOGIN
_CT: "application/json"
LOGIN
EMAIL
FIELD: "email"
_
_
LOGIN
PASSWORD
_
_FIELD: "password"
LOGIN
TENANT
FIELD: "tenant
id"
_
_
_
CSRF
HEADER
NAME: ""
_
_
CSRF
COOKIE
NAME: ""
_
_
API
KIND: "rest"
_
MESSAGES
_
URL: "https://app.boomnow.com/api/conversations/{{conversationId}}"
MESSAGES
METHOD: "GET"
_
SLA
MINUTES: "5"
_
COUNT
AI
SUGGESTION
AS
AGENT: "false"
_
_
_
_
# Pull the conversation from either workflow dispatch inputs or repository_dispatch
client
_payload.
# Power Automate's repository dispatch can attach a `conversation` or `conversationUrl`
field under client
_payload;
# if none are present this will evaluate to an empty string and the checker will fall back to the
default conversation ID.
CONVERSATION
_
INPUT: ${{ github.event.inputs.conversation ||
github.event.client_payload.conversation || github.event.client_payload.conversationUrl ||
github.event.client_payload.conversation_url }}
DEFAULT
CONVERSATION
_
_
ID: ${{ vars.DEFAULT_
CONVERSATION
_ID }}
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: "20"
- name: Install deps
run: |
if [ -f package-lock.json ]; then
npm ci
else
npm i
fi
- name: Run SLA checker
run: node check.mjs
