name: Boom SLA check (cron)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch: {}      # allow manual runs

concurrency:
  group: boom-sla-check
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_RUN: 1
      # non-secret repo variables (already set in your repo)
      LOGIN_URL:                  ${{ vars.LOGIN_URL }}
      LOGIN_METHOD:               ${{ vars.LOGIN_METHOD }}
      MESSAGES_URL:               ${{ vars.MESSAGES_URL }}
      MESSAGES_METHOD:            ${{ vars.MESSAGES_METHOD }}
      CONVERSATIONS_URL:          ${{ vars.CONVERSATIONS_URL }}
      CONVERSATIONS_METHOD:       ${{ vars.CONVERSATIONS_METHOD }}
      CONVERSATIONS_BODY:          ${{ vars.CONVERSATIONS_BODY }}
      SLA_MINUTES:                ${{ vars.SLA_MINUTES }}
      DEBUG:                      ${{ vars.DEBUG || '0' }}
      DEBUG_MESSAGES:             ${{ vars.DEBUG_MESSAGES }}
      COUNT_AI_SUGGESTION_AS_AGENT: ${{ vars.COUNT_AI_SUGGESTION_AS_AGENT }}

      # secrets (already in your repo)
      BOOM_USER:   ${{ secrets.BOOM_USER }}
      BOOM_PASS:   ${{ secrets.BOOM_PASS }}
      SMTP_HOST:   ${{ secrets.SMTP_HOST }}
      SMTP_PORT:   ${{ secrets.SMTP_PORT }}
      SMTP_USER:   ${{ secrets.SMTP_USER }}
      SMTP_PASS:   ${{ secrets.SMTP_PASS }}
      ALERT_TO:    ${{ secrets.ALERT_TO }}
      ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: .
        run: |
          ls -la
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Debug conversations endpoint
        if: env.DEBUG == '1'
        env:
          # Use whichever you already have configured
          CONVERSATIONS_URL: ${{ vars.CONVERSATIONS_URL || secrets.CONVERSATIONS_URL }}
        shell: bash
        run: |
          set -euo pipefail

          raw="${CONVERSATIONS_URL:-}"
          if [ -z "$raw" ]; then
            echo "::error::CONVERSATIONS_URL is empty"; exit 1
          fi

          # Sanitize: strip CR/LF/TAB and any pasted quotes/brackets
          url="$(printf '%s' "$raw" | tr -d '\r\n\t')"
          url="${url#<}"; url="${url%>}"
          url="${url#\"}"; url="${url%\"}"
          url="${url#\'}"; url="${url%\'}"

          # Encode spaces if any
          case "$url" in *" "*) url="${url// /%20}";; esac

          echo "Hitting (sanitized): $url"

          # Print raw bytes so hidden characters are visible in logs
          printf 'URL bytes (hex): '
          printf '%s' "$url" | od -An -t x1 | tr -d '\n'
          echo

          # Safe curl: disable globbing; follow redirects; fail clearly
          curl -sS -L --fail --show-error --globoff "$url" -w "\nHTTP %{http_code}\n"

      - name: Debug conversations endpoint (rebuild query)
        if: env.DEBUG == '1'
        shell: bash
        run: |
          set -euo pipefail
          base="https://app.boomnow.com/api/conversations/all"
          echo "Hitting (rebuilt with --get): $base ? all=true"
          curl -sS -L --fail --show-error --globoff --get "$base" \
            --data-urlencode "all=true" \
            -w "\nHTTP %{http_code}\n"

      - name: Run SLA checker
        working-directory: .
        run: node ./cron.mjs
