name: Boom SLA (API, REST)

on:
  workflow_dispatch:
    inputs:
      conversation_urls:
        description: "Comma-separated conversation URLs or IDs (UUIDs)"
        required: true
        type: string
      sla_min:
        description: "SLA minutes"
        required: false
        default: "5"
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i nodemailer

      - name: Run SLA checker
        env:
          # Boom API
          BOOM_LOGIN_URL: https://app.boomnow.com/api/login
          BOOM_API_BASE: https://app.boomnow.com/api
          BOOM_USER: ${{ secrets.BOOM_USER }}
          BOOM_PASS: ${{ secrets.BOOM_PASS }}
          BOOM_TENANT_ID: ${{ secrets.BOOM_TENANT_ID }}

          # Email / SMTP
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ALERT_TO:   ${{ secrets.ALERT_TO }}
          ALERT_CC:   ${{ secrets.ALERT_CC }}
          ALERT_FROM_NAME: ${{ secrets.ALERT_FROM_NAME }}

          # Heuristic (optional)
          AGENT_SIDE: ${{ secrets.AGENT_SIDE }}

          # 👇 Map workflow inputs → env vars the script reads
          INPUT_CONVERSATION_URLS: ${{ inputs.conversation_urls }}
          INPUT_SLA_MIN:          ${{ inputs.sla_min }}
        run: node check.mjs
