name: Deploy boom-notify
on:
  push:
    paths:
      - 'azure/boom-notify/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (function dir)
        run: npm ci
        working-directory: azure/boom-notify

      - name: Package function (zip)
        run: |
          cd azure/boom-notify
          zip -r ../functionapp.zip host.json boom-notify package.json package-lock.json
          ls -la ../functionapp.zip

      - name: ZipDeploy to Kudu (publish profile)
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}
        run: |
          set -euo pipefail
          USER=$(echo "$PUBLISH_PROFILE" | sed -n 's/.*publishMethod="ZipDeploy".*userName="\([^"\]*\)".*/\1/p' | head -n1)
          PWD=$(echo "$PUBLISH_PROFILE" | sed -n 's/.*publishMethod="ZipDeploy".*userPWD="\([^"\]*\)".*/\1/p' | head -n1)
          SCM=$(echo "$PUBLISH_PROFILE" | sed -n 's#.*publishMethod="ZipDeploy".*publishUrl="\([^"\]*\)".*#\1#p' | head -n1)
          if [ -z "$USER" ] || [ -z "$PWD" ] || [ -z "$SCM" ]; then
            echo "Publish profile secret missing or invalid."
            exit 1
          fi
          curl -fsSL -u "$USER:$PWD" \
            -H "Content-Type: application/zip" \
            --data-binary @azure/functionapp.zip \
            "$SCM/api/zipdeploy"

