name: Deploy boom-notify
on:
  push:
    paths:
      - 'azure/boom-notify/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (function dir)
        working-directory: azure/boom-notify
        run: npm ci

      - name: Package function (zip)
        working-directory: azure/boom-notify
        run: |
          rm -f ../functionapp.zip
          zip -r ../functionapp.zip host.json package.json boom-notify
          ls -lh ../functionapp.zip

      - name: ZipDeploy to Kudu (publish profile)
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}
        run: |
          set -euo pipefail
          PP_PATH=$(mktemp)
          echo "${PUBLISH_PROFILE}" > "$PP_PATH"
          USER=$(xmllint --xpath "string(//publishProfile/@userName)" "$PP_PATH")
          PASS=$(xmllint --xpath "string(//publishProfile/@userPWD)" "$PP_PATH")
          URL=$(xmllint  --xpath "string(//publishProfile/@publishUrl)" "$PP_PATH")
          rm -f "$PP_PATH"
          echo "Kudu endpoint: $URL"
          curl -sS -u "$USER:$PASS" -X POST "https://$URL/api/zipdeploy" --data-binary "@azure/functionapp.zip" | jq .
