name: Deploy boom-notify
on:
  push:
    paths:
      - 'azure/boom-notify/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (function dir)
        working-directory: azure/boom-notify
        run: npm ci

      - name: Package
        working-directory: azure/boom-notify
        run: npm pack
